server:
  port: 10001
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 200
      min-spare: 50
    connection-timeout: 5000ms
    accept-count: 100
    max-connections: 8192
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/tuitui?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
      minimum-idle: 50
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 5000
        max-idle: 5000
        min-idle: 2000
        max-wait: 5000ms
    connect-timeout: 5000ms
    password: 123456
  transaction:
    rollback-on-commit-failure: true
# 自定义 jwt 密钥
jwt:
  key: "F!$@#%#@$%GDSFGSDgsdf????$@#%@%@#$GDFSGDSFGDS"
  expiration-time: 1
